name: pipe_tsm
channels:
  - defaults
dependencies:
  - python=3.10
  - pip:
      - PyYaml
      - dask==2024.7.0
      - distributed==2024.7.0
      - dask-jobqueue==0.8.5
      - hipscat==0.3.7
      - hipscat-import==0.3.4
      - lsdb==0.2.8
      - tables_io==0.9.8
