name: pipe_tsm
channels:
  - defaults
dependencies:
  - python=3.10
  - pip:
      - PyYaml
      - dask==2024.7.0
      - distributed==2024.7.0
      - dask-jobqueue==0.8.5
      - lsdb==0.4.2
      - tables_io==0.9.10
