##################################################################
# Parameters file. Should follow the syntax defined in:
# http://docs.ansible.com/ansible/latest/YAMLSyntax.html
# More general reference: http://www.yaml.org/spec/1.2/spec.html

executor: 
  name: "slurm"
  args:
    instance:
      cores: 50
      processes: 1
      memory: "120GB"
      queue: "cpu"
      job_extra_directives:
        - "--propagate"
        - "--time=2:00:00"
    adapt:
      maximum_jobs: 10

inputs:
  specz:
    - path: "/scratch/users/luigi.silva/speczs-catalogs/processed/2dfgrs_final_release.parquet"
      internal_name: "001_2dfgrs_final_release"
      columns:
        id: "name"
        ra: "ra_j2000_deg"
        dec: "dec_j2000_deg"
        z: "z"
        z_flag: "quality"
        z_err: null
        survey: "survey_name"

    - path: "/scratch/users/luigi.silva/speczs-catalogs/processed/2dflens_final_release.parquet"
      internal_name: "002_2dflens_final_release"
      columns:
        id: "unique_id"
        ra: "RA"
        dec: "Dec"
        z: "z"
        z_flag: "qual"
        z_err: null
        survey: "survey_name"

    - path: "/scratch/users/luigi.silva/speczs-catalogs/processed/2mrs_v240.parquet"
      internal_name: "003_2mrs_v240"
      columns:
        id: "TMID"
        ra: "RA"
        dec: "DEC"
        z: "redshift"
        z_flag: null
        z_err: "redshift_err"
        survey: "survey_name"

    - path: "/scratch/users/luigi.silva/speczs-catalogs/processed/jades_dr3.parquet"
      internal_name: "004_jades_dr3"
      columns:
        id: "unique_id"
        ra: "RA_TARG"
        dec: "Dec_TARG"
        z: "z_Spec"
        z_flag: "z_Spec_flag"
        z_err: null
        survey: "survey_name"

    - path: "/scratch/users/luigi.silva/speczs-catalogs/processed/primus_dr1.parquet"
      internal_name: "005_primus_dr1"
      columns:
        id: "OBJNAME"
        ra: "RA"
        dec: "DEC"
        z: "Z"
        z_flag: "ZQUALITY"
        z_err: null
        survey: "survey_name"

base_dir: "/scratch/users/luigi.silva/pzserver_pipelines/combine_redshift_dedup/process001"
output_dir: "outputs"
logs_dir: "logs"
temp_dir: "temp"
output_format: "csv"
output_name: "crd"
combine_type: "concatenate_and_mark_duplicates" # Can be also "concatenate" or "concatenate_and_remove_duplicates"
flags_translation_file: flags_translation.yaml

param:
  debug: true