##################################################################
# Parameters file. Should follow the syntax defined in:
# http://docs.ansible.com/ansible/latest/YAMLSyntax.html
# More general reference: http://www.yaml.org/spec/1.2/spec.html

executor: 
  name: "local"   # or "slurm"
  args:
    n_workers: 2
    threads_per_worker: 2
    memory_limit: "1GiB"
  # args:
  #   instance:
  #     cores: 54
  #     processes: 1
  #     memory: "123GiB"
  #     queue: "cpu"
  #     job_extra_directives:
  #       - "--propagate"
  #       - "--time=2:00:00"
  #   adapt:
  #     maximum_jobs: 10

inputs:
  specz:
    - path: "<DATASETS_DIR>/specz.parquet"
      columns:
        ra: "ra"
        dec: "dec"
        z: "z"
    - path: "<DATASETS_DIR>/specz.parquet"
      columns:
        ra: "ra"
        dec: "dec"
        z: "z"

output_dir: "outputs"
output_name: "csc.parquet"

param:
  debug: true
